[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
rand = "0.8.5"
backend = { path= "../backend"}
serde_json = "1.0.59"
futures = "0.3.21"